name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          working-directory: C:/Users/200551/cypress-example-kitchensink/package-lock.json
          build: npm run build
          start: npm start
          browser: electron